kind = "web"
previewPath = "/"
title = "Notesy"
version = "1.0.0"
id = "artifacts/notesy"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25958

[services.development]
run = "pnpm --filter @workspace/notesy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/notesy", "run", "build" ]
publicDir = "artifacts/notesy/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25958"
BASE_PATH = "/"
